receivers:
  otlp:
    protocols:
      http:
      grpc: tms-otel-collector:4317
  filelog:
    include: ["/var/log/tms/*.json", "/var/log/nginx/access.log"]
    operators:
      - type: json_parser
        if: 'body matches "^{.*}$"'
        parse_from: body

processors:
  batch:
  attributes:
    actions:
      - key: Source
        value: "Otel-Collector"
        action: upsert

extensions:
  health_check:
  pprof:
  zpages:

exporters:
  prometheus:
    endpoint: "tms-prometheus:9090"
  loki:
    endpoint: "http://tms-loki:3100/loki/api/v1/push"
    default_labels_enabled:
      exporter: true
      job: true

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [filelog]
      processors: [attributes]
      exporters: [loki]