receivers:
  otlp:
    protocols:
      http:
      grpc:
  filelog:
    include: ["/var/log/tms/*.json", "/var/log/nginx/access.log"]
    operators:
      - type: json_parser
        if: 'body matches "^{.*}$"'
        parse_from: body

processors:
  batch:
  attributes:
    actions:
      - key: Source
        value: "Otel-Collector"
        action: upsert

extensions:
  health_check:
  pprof:
  zpages:

exporters:
  debug:
    verbosity: detailed
  otlphttp/prometheus:
    endpoint: http://tms-prometheus:9090/api/v1/otlp
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: http://http://tms-prometheus:9090/api/v1/otlp:9090/api/v1/write
    tls:
      insecure: true
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: "http://tms-loki:3100/loki/api/v1/push"
    default_labels_enabled:
      exporter: true
      job: true

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, debug]
    logs:
      receivers: [filelog]
      processors: [attributes]
      exporters: [loki]