spring:
  application:
    name: TMS
  threads:
    virtual:
      enabled: true
  main:
    lazy-initialization: true
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

management:
  endpoint:
    health:
      probes:
        add-additional-paths: true
        enabled: true
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS}

server:
  http2:
    enabled: true
  shutdown: graceful
  compression:
    enabled: true

modules:
  commons:
    enabled: ${MODULES_COMMONS_ENABLED}
  company:
    enabled: ${MODULES_COMPANY_ENABLED}
  order:
    enabled: ${MODULES_ORDER_ENABLED}

tms-logging:
  format: ${LOG_FORMAT}
  console:
    enabled: 'true'
  file:
    enabled: 'false'
    path: tmp/logs/${spring.application.name}
    name: ${spring.application.name}
    max-history-days: 5
    total-size-cap: 3GB
    max-size: 10MB
    pattern:
      rolling-file-name: ${tms-logging.file.path}/${tms-logging.file.name}-%d{yyyy-MM-dd}-%i

otel:
  service:
    name: ${spring.application.name}-OTEL-SERVICE
  metrics:
    exporter: otlp
  traces:
    exporter: otlp
  logs:
    exporter: otlp
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://0.0.0.0:4317
  sdk:
    disabled: ${OTEL_SDK_DISABLED}
  instrumentation:
    jdbc:
      enabled: true
    spring-web:
      enabled: false
    micrometer:
      enabled: true
