spring:
  application:
    name: TMS
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS}