apiVersion: 1

datasources:
  - name: Tms-Loki
    type: loki
    access: proxy
    url: http://tms-loki:3100
    version: 1
    editable: false
    isDefault: true
  - name: Tms-Prometheus
    type: prometheus
    access: proxy
    url: http://tms-prometheus:9090
    isDefault: false
    editable: true