pg_stat_statements_custom:
  query: |
    SELECT
      queryid,
      query,
      calls,
      total_exec_time,
      mean_exec_time
    FROM pg_stat_statements
    ORDER BY total_exec_time DESC
    LIMIT 5;
  metrics:
    - queryid:
        usage: "LABEL"
        description: "ID da query"
    - query:
        usage: "LABEL"
        description: "Texto da query (até 100 chars)"
    - calls:
        usage: "COUNTER"
        description: "Número de execuções"
    - total_exec_time:
        usage: "GAUGE"
        description: "Tempo total de execução (ms)"
    - mean_exec_time:
        usage: "GAUGE"
        description: "Tempo médio de execução (ms)"