@server = http://localhost:8080
@now = {{ $timestamp }}

### Create ShipmentOrder
POST {{server}}/shipmentorders
Content-Type: application/json
Accept: application/json

{
  "companyId": "{{companyId}}",
  "externalId": "externalId_{{$uuid}}",
  "createdAt": "{{now}}"
}

> {% client.global.set("shipmentOrderId", response.body.shipmentOrderId) %}

### Get By company
GET {{server}}/shipmentorders/company/{{companyId}}?page=3&size=1
Accept: application/json